pub const TBL_SITE_ID: &'static str = "__crsql_siteid";
pub const TBL_SCHEMA: &'static str = "crsql_master";
pub const TBL_DB_VERSIONS: &'static str = "crsql_dbversions_count";
pub const CLOCK_TABLES_SELECT: &'static str =
    "SELECT tbl_name FROM sqlite_master WHERE type='table' AND tbl_name LIKE '%__crsql_clock'";
pub const CRSQLITE_VERSION_0_15_0: i32 = 150000;
pub const CRSQLITE_VERSION: i32 = 150000;
pub const SITE_ID_LEN: i32 = 16;
pub const ROWID_SLAB_SIZE: i64 = 10000000000000;
pub const MIN_POSSIBLE_DB_VERSION: i64 = 0;
pub const MAX_TBL_NAME_LEN: i32 = 2048;
